/*
 * Copyright (c) 2005-2011 Atheros Communications Inc.
 * Copyright (c) 2011-2013 Qualcomm Atheros, Inc.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef _HW_H_
#define _HW_H_

#define TARGET_TYPE_AR9888	7

/* Supported FW version */
#define SUPPORTED_FW_MAJOR	1
#define SUPPORTED_FW_MINOR	0
#define SUPPORTED_FW_RELEASE	0
#define SUPPORTED_FW_BUILD	548

/* AR9888 1.0 definitions */
#define AR9888_HW_1_0_VERSION		0x4000002c
#define AR9888_HW_1_0_FW_DIR		"ath10k/AR9888/hw1.0"
#define AR9888_HW_1_0_FW_FILE		"athwlan_AR9888v1.bin"
#define AR9888_HW_1_0_OTP_FILE		"otp.bin"
#define AR9888_HW_1_0_BOARD_DATA_FILE	"fakeBoardData_AR6004.bin"
#define AR9888_HW_1_0_PATCH_LOAD_ADDR	0x1234

/* AR9888 2.0 definitions */
#define AR9888_HW_2_0_VERSION		0x4100016c
#define AR9888_HW_2_0_FW_DIR		"ath10k/AR9888/hw2.0"
#define AR9888_HW_2_0_FW_FILE		"athwlan_AR9888v2.bin"
#define AR9888_HW_2_0_OTP_FILE		"otp.bin"
#define AR9888_HW_2_0_BOARD_DATA_FILE	"fakeBoardData_AR9888v2.bin"
#define AR9888_HW_2_0_PATCH_LOAD_ADDR	0x1234

#define TARGET_NUM_VDEV				16
#define TARGET_NUM_PEER_AST			2
#define TARGET_WDS_ENTRIES			32
#define TARGET_DMA_BURST_SIZE			0
#define TARGET_MAC_AGGR_DELIM			0
#define TARGET_AST_SKID_LIMIT			16
#define TARGET_NUM_PEERS			16
#define TARGET_NUM_OFFLOAD_PEERS		0
#define TARGET_NUM_PEER_KEYS			2
#define TARGET_NUM_TIDS	(2 * (TARGET_NUM_PEERS + TARGET_NUM_VDEV))
#define TARGET_TX_CHAIN_MASK			0x7
#define TARGET_RX_CHAIN_MASK			0x7
#define TARGET_RX_TIMEOUT_LO_PRI		100
#define TARGET_RX_TIMEOUT_HI_PRI		40
#define TARGET_RX_DECAP_MODE			(0x2)
#define TARGET_RX_DECAP_MODE_NWIFI		(0x1)
#define TARGET_SCAN_MAX_REQS			0x4
#define TARGET_BMISS_OFFLOAD_MAX_VDEV		0x3
#define TARGET_ROAM_OFFLOAD_MAX_VDEV		0x3
#define TARGET_ROAM_OFFLOAD_MAX_PROFILES	0x8
#define TARGET_GTK_OFFLOAD_MAX_VDEV		0x3
#define TARGET_NUM_MCAST_GROUPS			0
#define TARGET_NUM_MCAST_TABLE_ELEMS		0
#define TARGET_MCAST2UCAST_MODE			0 /* disabled */
#define TARGET_TX_DBG_LOG_SIZE			1024 /* bytes */
#define TARGET_RX_SKIP_DEFRAG_TIMEOUT_DUP_DETECTION_CHECK 0
#define TARGET_VOW_CONFIG			0
#define TARGET_NUM_MSDU_DESC			(1024 + 400)

#endif /* _HW_H_ */
